#!/bin/bash
#SBATCH --job-name=self_distill
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
#SBATCH --time=0-03:00:00
#SBATCH --nodes=1                       # number of nodes
#SBATCH --gpus-per-task=4               # number of gpus per node
#SBATCH --cpus-per-task=24              # number of cpus per gpu
#SBATCH --mem=0                         # all memory per node
#SBATCH --ntasks-per-node=1             # crucial - only 1 task per node!
#SBATCH --constraint=80gb               # constraints
#SBATCH --exclude=cn-k[001-002]
#SBATCH --partition=short-unkillable

module load anaconda/3
export HF_HOME=$SCRATCH/

conda activate $SCRATCH/arena-capstone/venv
export OMP_NUM_THREADS=4

path_to_model=""
output_dir=""

python main.py \
  --model_name $path_to_model \
  --output_dir $output_dir \
  --learning_rate 2e-5 \
  --num_train_epochs 1